### ISSUE TITLE
peerDependencies for vue?

### ISSUE THREAD

**Issue by thomasleveil** [northwalker/vue-hotel-datepicker#1]
Hi, 

Thank you for maintaining this great component. There are not a lot to choose from for this use case. 

Reviewing the v2.0.0 I noticed you declared `vue` in the `dependencies` section of _packages.json_. Shouldn't it be declared in the [`peerDependencies`](https://nodejs.org/en/blog/npm/peer-dependencies/#the-solution-peer-dependencies) section?

**Comment by northwalker** [comment]
Hi @thomasleveil 
Thanks for your advice! dependencies has updated at v2.0.1
