### ISSUE TITLE
onfocus event not supported

### ISSUE THREAD

**Issue by saniales** [northwalker/vue-hotel-datepicker#13]
From an UI point of view it would be awesome to support tab enter like events

IMHO a very simple solution is to treat the `@focus` event as a click.

Do you have any solution to do that from a prop point of view?

**Comment by northwalker** [comment]
I have merged PR: https://github.com/northwalker/vue-hotel-datepicker/pull/15,
and publish new version `2.0.7`. 
Thanks for your help @saniales and @TobiasJ
