### ISSUE TITLE
Max night issue

### ISSUE THREAD

**Issue by depus9** [northwalker/vue-hotel-datepicker#4]
<VueHotelDatepicker :ref="datepickerId" :datepickerd="datepickerId" :selectForward="selectForward" :maxNights="maxNights" v-on:update="getDate($event)"
                                            format="MM-DD-YYYY" :placeholder="placeholder" 

is there anything wrong?

**Comment by depus9** [comment]
"<VueHotelDatepicker :ref="datepickerId" :datepickerd="datepickerId" :selectForward="selectForward" :maxNights="maxNights" v-on:update="getDate($event)"
                                            format="MM-DD-YYYY" :placeholder="placeholder" />"

**Comment by depus9** [comment]
VueHotelDatepicker :ref="datepickerId" :datepickerd="datepickerId" :selectForward="selectForward" :maxNights="maxNights" v-on:update="getDate($event)"
                                            format="MM-DD-YYYY" :placeholder="placeholder"

**Comment by northwalker** [comment]
Hi @depus9, 
what's the package version you are using?
some attributes seems not supported (ie: datepickerId) at current version, please update package version for usage.
