### ISSUE TITLE
Found some issues

### ISSUE THREAD

**Issue by etenente** [northwalker/vue-hotel-datepicker#8]
Hello there!

First of all, nice component!
I've found 2 issues related to the documentation vs. real implementation:

> Prop 'separator' have a typo. The documentation states it is 'separator' but it is implementated as 'seperator'.
> The documentation states this two properties 'maxNights' and 'minNights' ending with the letter 's'. It seems it's implementated without the 's' as 'maxNight' and 'minNight'.

I also found another little bug. If you set your min date to the first day of 2019, for example, the control disable the 'previous arrow' for every start of year.

Best regards!

**Comment by northwalker** [comment]
That typo error has fixed at `2.0.4`.

@etenente  Can you explain another bug more clearly or give an example?
> I also found another little bug. If you set your min date to the first day of 2019, for example, the control disable the 'previous arrow' for every start of year.

Thank you very mush for report and help!

**Comment by etenente** [comment]
To simulate the issue:
- On the demo (https://northwalker.github.io/vue-hotel-datepicker/) navigate to JAN 2020 on 1st controller. Once you do it, there is no way to navigate back. It seems it´s related to every start of year.

**Comment by northwalker** [comment]
oh......That's a funny bug. lol
This bug fixed at `2.0.6`. 
Thanks @etenente very much for your report!!
