### ISSUE TITLE
Maximum night exceed because user can select dates before start date

### ISSUE THREAD

**Issue by tapitapeh** [northwalker/vue-hotel-datepicker#9]
![image](https://user-images.githubusercontent.com/7647443/61577641-cab7fc00-ab1c-11e9-98ae-c0be080a2324.png)

Hi,
As screenshot attached, user can select date before start date so it exceed maximum nights

**Comment by northwalker** [comment]
This issue fixed at `2.0.4`.
Thanks for your reporting!
